# Generated by Django 4.1 on 2022-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TD', 'TO_DO'), ('IP', 'IN_PROGRESS'), ('C', 'COMPLETED')], default='TD', max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('W', 'WEAK'), ('M', 'MEDIUM'), ('H', 'HIGH')], default='W', max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('B', 'BUG'), ('U', 'UPGRADE'), ('T', 'TASK')], default='B', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('iOS', 'iOS'), ('android', 'android')], max_length=32),
        ),
    ]
