# Generated by Django 4.1 on 2022-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0002_remove_contributor_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('BE', 'back-end'), ('FE', 'front-end'), ('iOS', 'iOS'), ('AD', 'android')], max_length=32),
        ),
    ]
