# Generated by Django 4.1 on 2022-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0003_alter_project_project_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique contributor'),
        ),
    ]
